---
- name: Generate CMDB Device Count Excel Report
  hosts: localhost
  gather_facts: no

  vars:
    netbox_url: "{{ lookup('env', 'NETBOX_API') | default('https://netbox.example.com', true) }}"
    netbox_token: "{{ lookup('env', 'NETBOX_TOKEN') | default(omit, true) }}"

  tasks:

    - name: Ensure 'reportlab' is installed
      pip:
        name: reportlab
        executable: pip3

    - name: Ensure 'requests' is installed
      pip:
        name: requests
        executable: pip3

    - name: Ensure openpyxl is installed
      pip:
        name: openpyxl
        executable: pip3

    - name: Run device report script
      environment:
        NETBOX_URL: "{{ netbox_url }}"
        NETBOX_TOKEN: "{{ netbox_token }}"
      script: get_netbox_device_report.py

    - name: Fetch generated Excel report to AWX artifacts directory
      fetch:
        src: /runner/cmdb_device_report.xlsx
        dest: cmdb_device_report.xlsx
        flat: yes

    - name: Email the PDF report
      community.general.mail:
        host: smtp.timberlinkaustralia.com.au    
        port: 25               
        to: cjones@timberlinkaustralia.com.au        
        from: awx@timberlinkaustralia.com.au       
        subject: "CMDB Device Report"
        body: "Attached is the latest CMDB device count Excel report."
        attach:
          - /runner/cmdb_device_report.xlsx
      delegate_to: localhost
